import type { RulesConfig } from '@eslint/core';
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';

const { configs } = js;
const customIgnore = [
  'capitalized-comments',
  'func-style',
  'no-magic-numbers',
  'no-ternary',
  'no-unused-vars',
  'no-use-before-define',
  'no-void',
  'no-warning-comments',
  'one-var',
  'sort-imports',
  'class-methods-use-this',
  'accessor-pairs',
  'new-cap',
];
const recommended = Object.keys(configs.recommended.rules);
const customError = Object.keys(configs.all.rules)
  .filter(rule => !customIgnore.includes(rule))
  .filter(rule => !recommended.includes(rule))
  .reduce<RulesConfig>((prev, curr) => ({ ...prev, [curr]: 'error' }), {});

export const eslint = defineConfig(
  js.configs.recommended,
  globalIgnores(
    ['dist', 'docs', 'coverage', '.angular'],
    '@eslint/js/custom-ignore-directory',
  ),
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
      reportUnusedInlineConfigs: 'error',
    },
  },
  {
    name: '@eslint/js/custom',
    rules: {
      ...customError,
      'id-length': ['error', { exceptions: ['i', 'x', 'y'] }],
      'no-debugger': 'off',
      'no-duplicate-imports': ['error', { allowSeparateTypeImports: true }],
      ///
      'no-alert': 'off',
      'no-array-constructor': 'off',
      'no-await-in-loop': 'off',
      'no-bitwise': 'off',
      'no-caller': 'off',
      'no-console': 'off',
      'no-constructor-return': 'off',
      'no-continue': 'off',
      'no-div-regex': 'off',
      'no-else-return': 'off',
      'no-empty-function': 'off',
      'no-eq-null': 'off',
      'no-eval': 'off',
      'no-extend-native': 'off',
      'no-extra-bind': 'off',
      'no-extra-label': 'off',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'off',
      'no-implied-eval': 'off',
      'no-inline-comments': 'off',
      'no-inner-declarations': 'off',
      'no-invalid-this': 'off',
      'no-iterator': 'off',
      'no-label-var': 'off',
      'no-labels': 'off',
      'no-lone-blocks': 'off',
      'no-lonely-if': 'off',
      'no-loop-func': 'off',
      'no-multi-assign': 'off',
      'no-multi-str': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new': 'off',
      'no-new-func': 'off',
      'no-new-wrappers': 'off',
      'no-object-constructor': 'off',
      'no-octal-escape': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-promise-executor-return': 'off',
      'no-proto': 'off',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'no-return-assign': 'off',
      'no-script-url': 'off',
      'no-self-compare': 'off',
      'no-sequences': 'off',
      'no-shadow': 'off',
      'no-template-curly-in-string': 'off',
      'no-throw-literal': 'off',
      'no-unassigned-vars': 'off',
      'no-undef-init': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unmodified-loop-condition': 'off',
      'no-unneeded-ternary': 'off',
      'no-unreachable-loop': 'off',
      'no-unused-expressions': 'off',
      'no-useless-assignment': 'off',
      'no-useless-call': 'off',
      'no-useless-computed-key': 'off',
      'no-useless-concat': 'off',
      'no-useless-constructor': 'off',
      'no-useless-rename': 'off',
      'no-useless-return': 'off',
      'no-var': 'off',
      'object-shorthand': 'off',
      'operator-assignment': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-const': 'off',
      'prefer-destructuring': 'off',
      'prefer-exponentiation-operator': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-numeric-literals': 'off',
      'prefer-object-has-own': 'off',
      'prefer-object-spread': 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-regex-literals': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-template': 'off',
      'preserve-caught-error': 'off',
      radix: 'off',
      'require-atomic-updates': 'off',
      'require-await': 'off',
      'require-unicode-regexp': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      strict: 'off',
      'symbol-description': 'off',
      'unicode-bom': 'off',
      'vars-on-top': 'off',
      yoda: 'off',
    },
  },
  {
    files: ['**/*.spec.ts'],
    name: '@eslint/js/custom-spec',
    rules: {
      'id-length': [
        'error',
        { exceptions: ['i', 'x', 'y'], properties: 'never' },
      ],
      'init-declarations': 'off',
      'max-lines-per-function': 'off',
    },
  },
);
